### ISSUE TITLE
Just something to check... - avoid multiple redirects

### ISSUE THREAD

**Issue by ranguard** [metacpan/sco-redirect#1]
Currently (not this code!): 

http://search.Mcpan.org/~lbrocard/Data-Page-2.02/lib/Data/Page.pm
Does a HTTP_FOUND to https://metacpan.org/module/lbrocard/Data-Page-2.02/lib/Data/Page.pm
Which does a PERMANENT to /pod/release/LBROCARD/Data-Page-2.02/lib/Data/Page.pm

Would be nice to skip the extra step if that's possible?

Also as many PERMANENT links as possible are good :)

**Comment by haarg** [comment]
Most of the redirects use 301, however there are a number where we don't have equivalent endpoints.  All of the redirects should be to the final pages and not need additional redirects.
