### ISSUE TITLE
Incorrect redirect of script documentation

### ISSUE THREAD

**Issue by Grinnz** [metacpan/sco-redirect#4]
The redirect of http://search.cpan.org/~kazuho/Server-Starter-0.11/start_server - http://search.mcpan.org/~kazuho/Server-Starter-0.11/start_server goes to https://metacpan.org/source/KAZUHO/Server-Starter-0.11/start_server (showing the script's source) but it should go to https://metacpan.org/pod/release/KAZUHO/Server-Starter-0.11/start_server (showing the script's documentation).

**Comment by Grinnz** [comment]
This may be because https://metacpan.org/pod/release/KAZUHO/Server-Starter-0.11/script/start_server does not exist but there is pod in that version of the script...

**Comment by haarg** [comment]
I have work in progress code to deal with this.  The current check for files with pod uses the file extension, which is not accurate.  It needs to check through the API instead.

**Comment by haarg** [comment]
Fixed.
