### ISSUE TITLE
missing redirect from http://search.mcpan.org/~miyagawa/App-cpanminus-1.7907-TRIAL/bin/cpanm

### ISSUE THREAD

**Issue by sjn** [metacpan/sco-redirect#5]
Link shown on http://search.cpan.org/~miyagawa/App-cpanminus-1.7907-TRIAL/bin/cpanm ends in a 404.

**Comment by haarg** [comment]
This is due to not recognizing the release name as a release name rather than dist name, because of the -TRIAL suffix.  Parsing the names using CPAN::DistnameInfo should resolve this.

**Comment by haarg** [comment]
Fixed.
