### ISSUE TITLE
Redirect for /dist/Test-Simple/lib/Test/Tutorial.pod go boom

### ISSUE THREAD

**Issue by ranguard** [metacpan/sco-redirect#7]
Not sure if actually the redirector, or just where it's pointing to that has an issue:

http://search.mcpan.org/dist/Test-Simple/lib/Test/Tutorial.pod

**Comment by haarg** [comment]
I'm not seeing any issues here.  It's redirecting to https://metacpan.org/pod/distribution/Test-Simple/lib/Test/Tutorial.pod

Where are you seeing it redirect to?  And how is that failing?

**Comment by ranguard** [comment]
Hmm, seems to be intermittent and on IRC others are reporting them (but this is a MC-Web issue - so closing this)
